# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the PG gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: unicode
  database: textme
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: textme
  pool: 5
  username: postgres
